Unit/simfrom/config/routes.rb
Rails.application.routes.draw do
  resources :simplefroms
  root 'simplefroms#index'

end

Unit/simfrom/app/models/role.rb
class Role < ActiveRecord::Base
  has_many :simpleform
end

Unit/simfrom/app/models/simplefrom.rb
class Simplefrom < ActiveRecord::Base
	enum remember_me: { false: 0, true: 1 }
	belongs_to :role
end

Unit/simfrom/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Unit/simfrom/app/controllers/simplefroms_controller.rb
class SimplefromsController < ApplicationController
  before_action :set_simplefrom, only: [:show, :edit, :update, :destroy]

  # GET /simplefroms
  # GET /simplefroms.json
  def index
    @simplefroms = Simplefrom.all
  end

  # GET /simplefroms/1
  # GET /simplefroms/1.json
  def show
  end

  # GET /simplefroms/new
  def new
    @simplefrom = Simplefrom.new
  end

  # GET /simplefroms/1/edit
  def edit
  end

  # POST /simplefroms
  # POST /simplefroms.json
  def create
    @simplefrom = Simplefrom.new(simplefrom_params)

    respond_to do |format|
      if @simplefrom.save
        format.html { redirect_to @simplefrom, notice: 'Simplefrom was successfully created.' }
        format.json { render :show, status: :created, location: @simplefrom }
      else
        format.html { render :new }
        format.json { render json: @simplefrom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simplefroms/1
  # PATCH/PUT /simplefroms/1.json
  def update
    respond_to do |format|
      if @simplefrom.update(simplefrom_params)
        format.html { redirect_to @simplefrom, notice: 'Simplefrom was successfully updated.' }
        format.json { render :show, status: :ok, location: @simplefrom }
      else
        format.html { render :edit }
        format.json { render json: @simplefrom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simplefroms/1
  # DELETE /simplefroms/1.json
  def destroy
    @simplefrom.destroy
    respond_to do |format|
      format.html { redirect_to simplefroms_url, notice: 'Simplefrom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simplefrom
      @simplefrom = Simplefrom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simplefrom_params
      params.require(:simplefrom).permit(:name, :email, :year, :remember_me, :role_id)
    end
end

Unit/simfrom/app/helpers/application_helper.rb
module ApplicationHelper
end

Unit/simfrom/app/helpers/simplefroms_helper.rb
module SimplefromsHelper
end

Unit/simfrom/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simfrom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Unit/simfrom/app/views/simplefroms/_form.html.erb
<%= simple_form_for(@simplefrom) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :year %>
   	<%= f.input :remember_me,     as: :radio_buttons %>
   	<%= f.collection_select(:role_id,  Role.all, :id, :name) %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Unit/simfrom/app/views/simplefroms/edit.html.erb
<h1>Editing Simplefrom</h1>

<%= render 'form' %>

<%= link_to 'Show', @simplefrom %> |
<%= link_to 'Back', simplefroms_path %>

Unit/simfrom/app/views/simplefroms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Simplefroms</h1>

<table class="table hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Year</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @simplefroms.each do |simplefrom| %>
      <tr>
        <td><%= simplefrom.name %></td>
        <td><%= simplefrom.email %></td>
        <td><%= simplefrom.year %></td>
        <td><%= simplefrom.role_id %></td>
        <td><%= link_to 'Show', simplefrom %></td>
        <td><%= link_to 'Edit', edit_simplefrom_path(simplefrom) %></td>
        <td><%= link_to 'Destroy', simplefrom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Simplefrom', new_simplefrom_path %>

Unit/simfrom/app/views/simplefroms/new.html.erb
<h1>New Simplefrom</h1>

<%= render 'form' %>

<%= link_to 'Back', simplefroms_path %>

Unit/simfrom/app/views/simplefroms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @simplefrom.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @simplefrom.email %>
</p>

<p>
  <strong>Year:</strong>
  <%= @simplefrom.year %>
</p>

<%= link_to 'Edit', edit_simplefrom_path(@simplefrom) %> |
<%= link_to 'Back', simplefroms_path %>